"""
Script to populate the database with auto listings
Run with: python add_auto_listings.py
"""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone
import os
from dotenv import load_dotenv

load_dotenv()

MONGO_URL = os.getenv("MONGO_URL", "mongodb://localhost:27017")

# Real car images from Unsplash
CAR_IMAGES = [
    'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',  # BMW
    'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',  # Mercedes white
    'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&q=80',  # Mercedes black
    'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&q=80',  # Porsche white
    'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',  # Porsche 911
    'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80',  # BMW blue
    'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80',  # Lamborghini
    'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80',  # Corvette
    'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80',  # Tesla
    'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80',  # Classic car
    'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80',  # Ferrari
    'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800&q=80',  # Audi
    'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',  # VW Golf
    'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80',  # SUV
    'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',  # Honda
]

AUTO_LISTINGS = [
    {
        "id": "auto_1",
        "user_id": "seller_1",
        "title": "BMW 320i M Sport - Full Service History",
        "description": "Excellent condition BMW 3 Series with full service history. This stunning vehicle comes with the M Sport package, featuring aggressive styling, sport suspension, and premium interior upgrades. The car has been meticulously maintained with all services done at authorized BMW dealers. Features include LED headlights, navigation system, heated seats, parking sensors, and much more.",
        "price": 28500,
        "negotiable": True,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[0], CAR_IMAGES[5]],
        "location": "Berlin, Germany",
        "city": "Berlin",
        "distance": 5,
        "status": "active",
        "featured": True,
        "boosted": False,
        "views": 237,
        "favorites_count": 45,
        "make": "BMW",
        "model": "320i",
        "year": 2021,
        "mileage": 35000,
        "fuelType": "Petrol",
        "transmission": "Automatic",
        "bodyType": "Sedan",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": True,
        "exchangePossible": False,
        "financingAvailable": True,
        "seller": {
            "user_id": "seller_1",
            "name": "AutoHaus Berlin",
            "phone": "+49301234567",
            "whatsapp": "+49301234567",
            "rating": 4.8,
            "verified": True,
            "sellerType": "dealer",
            "memberSince": "2020-01-15",
            "allowsOffers": True,
            "preferredContact": "whatsapp",
        },
    },
    {
        "id": "auto_2",
        "user_id": "seller_2",
        "title": "Mercedes-Benz C200 AMG Line",
        "description": "Stunning C-Class with AMG styling package. This elegant sedan combines luxury with sportiness. Features include AMG body kit, 19-inch alloy wheels, panoramic sunroof, MBUX infotainment system, and premium leather interior. Low mileage and accident-free.",
        "price": 32900,
        "negotiable": True,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[1], CAR_IMAGES[2]],
        "location": "Munich, Germany",
        "city": "Munich",
        "distance": 12,
        "status": "active",
        "featured": False,
        "boosted": True,
        "views": 189,
        "favorites_count": 32,
        "make": "Mercedes",
        "model": "C200",
        "year": 2022,
        "mileage": 18000,
        "fuelType": "Petrol",
        "transmission": "Automatic",
        "bodyType": "Sedan",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": True,
        "exchangePossible": True,
        "financingAvailable": True,
        "seller": {
            "user_id": "seller_2",
            "name": "Premium Cars Munich",
            "phone": "+49891234567",
            "rating": 4.9,
            "verified": True,
            "sellerType": "certified",
            "memberSince": "2019-05-20",
        },
    },
    {
        "id": "auto_3",
        "user_id": "seller_3",
        "title": "Volkswagen Golf GTI - Low Mileage",
        "description": "Hot hatch legend! This Golf GTI delivers pure driving pleasure with its turbocharged engine and precise handling. Features include sport seats, digital cockpit, adaptive chassis control, and the iconic GTI styling.",
        "price": 24500,
        "negotiable": False,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[12]],
        "location": "Hamburg, Germany",
        "city": "Hamburg",
        "distance": 8,
        "status": "active",
        "featured": False,
        "boosted": False,
        "views": 156,
        "favorites_count": 28,
        "make": "Volkswagen",
        "model": "Golf GTI",
        "year": 2020,
        "mileage": 28000,
        "fuelType": "Petrol",
        "transmission": "Manual",
        "bodyType": "Hatchback",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": False,
        "exchangePossible": False,
        "financingAvailable": False,
        "seller": {
            "user_id": "seller_3",
            "name": "Max M.",
            "phone": "+49401234567",
            "rating": 4.5,
            "verified": False,
            "sellerType": "individual",
            "memberSince": "2022-03-10",
        },
    },
    {
        "id": "auto_4",
        "user_id": "seller_4",
        "title": "Audi Q5 S-Line Quattro - Full Options",
        "description": "Luxury SUV with all-wheel drive. This Q5 comes fully loaded with S-Line exterior, virtual cockpit, Bang & Olufsen sound system, Matrix LED headlights, and quattro all-wheel drive for confident driving in all conditions.",
        "price": 45900,
        "negotiable": True,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[11], CAR_IMAGES[13]],
        "location": "Frankfurt, Germany",
        "city": "Frankfurt",
        "distance": 15,
        "status": "active",
        "featured": True,
        "boosted": False,
        "views": 312,
        "favorites_count": 67,
        "make": "Audi",
        "model": "Q5",
        "year": 2023,
        "mileage": 12000,
        "fuelType": "Diesel",
        "transmission": "Automatic",
        "bodyType": "SUV",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": True,
        "exchangePossible": True,
        "financingAvailable": True,
        "seller": {
            "user_id": "seller_4",
            "name": "Audi Zentrum Frankfurt",
            "phone": "+49691234567",
            "rating": 5.0,
            "verified": True,
            "sellerType": "certified",
            "memberSince": "2018-09-01",
        },
    },
    {
        "id": "auto_5",
        "user_id": "seller_5",
        "title": "Toyota Camry Hybrid - Eco Champion",
        "description": "Fuel-efficient hybrid sedan perfect for daily commuting. This Camry offers excellent fuel economy, a comfortable ride, and Toyota reliability. Features include adaptive cruise control, lane departure warning, and premium JBL audio system.",
        "price": 26800,
        "negotiable": True,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[9]],
        "location": "Cologne, Germany",
        "city": "Cologne",
        "distance": 20,
        "status": "active",
        "featured": False,
        "boosted": False,
        "views": 98,
        "favorites_count": 15,
        "make": "Toyota",
        "model": "Camry",
        "year": 2022,
        "mileage": 22000,
        "fuelType": "Hybrid",
        "transmission": "Automatic",
        "bodyType": "Sedan",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": False,
        "exchangePossible": False,
        "financingAvailable": True,
        "seller": {
            "user_id": "seller_5",
            "name": "Sarah K.",
            "phone": "+49221234567",
            "rating": 4.7,
            "verified": True,
            "sellerType": "individual",
            "memberSince": "2021-11-05",
        },
    },
    {
        "id": "auto_6",
        "user_id": "seller_6",
        "title": "Tesla Model 3 Long Range - Autopilot",
        "description": "Electric vehicle with full self-driving capability. This Model 3 offers impressive range, instant acceleration, and cutting-edge technology. Features include Autopilot, premium interior, 15-inch touchscreen, and over-the-air updates.",
        "price": 38500,
        "negotiable": False,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[8]],
        "location": "Stuttgart, Germany",
        "city": "Stuttgart",
        "distance": 25,
        "status": "active",
        "featured": True,
        "boosted": True,
        "views": 456,
        "favorites_count": 89,
        "make": "Tesla",
        "model": "Model 3",
        "year": 2023,
        "mileage": 8000,
        "fuelType": "Electric",
        "transmission": "Automatic",
        "bodyType": "Sedan",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": True,
        "exchangePossible": True,
        "financingAvailable": True,
        "seller": {
            "user_id": "seller_6",
            "name": "EV Motors Stuttgart",
            "phone": "+49711234567",
            "rating": 4.9,
            "verified": True,
            "sellerType": "dealer",
            "memberSince": "2020-06-15",
        },
    },
    {
        "id": "auto_7",
        "user_id": "seller_7",
        "title": "Ford Mustang GT 5.0 V8 - Muscle Car",
        "description": "American muscle with throaty V8 engine. This Mustang GT delivers raw power and iconic styling. Features include 5.0L V8 engine, manual transmission, Brembo brakes, and active exhaust system.",
        "price": 42000,
        "negotiable": True,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[10], CAR_IMAGES[7]],
        "location": "Düsseldorf, Germany",
        "city": "Düsseldorf",
        "distance": 18,
        "status": "active",
        "featured": False,
        "boosted": False,
        "views": 234,
        "favorites_count": 56,
        "make": "Ford",
        "model": "Mustang GT",
        "year": 2021,
        "mileage": 15000,
        "fuelType": "Petrol",
        "transmission": "Manual",
        "bodyType": "Coupe",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": False,
        "exchangePossible": True,
        "financingAvailable": False,
        "seller": {
            "user_id": "seller_7",
            "name": "Classic Cars NRW",
            "phone": "+49211234567",
            "rating": 4.6,
            "verified": True,
            "sellerType": "dealer",
            "memberSince": "2019-02-28",
        },
    },
    {
        "id": "auto_8",
        "user_id": "seller_8",
        "title": "Porsche 911 Carrera - Iconic Sports Car",
        "description": "The legendary 911 in pristine condition. This Carrera combines timeless design with modern performance. Features include Sport Chrono package, PASM suspension, Porsche Communication Management, and premium leather interior.",
        "price": 89900,
        "negotiable": True,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[3], CAR_IMAGES[4]],
        "location": "Berlin, Germany",
        "city": "Berlin",
        "distance": 3,
        "status": "active",
        "featured": True,
        "boosted": True,
        "views": 678,
        "favorites_count": 123,
        "make": "Porsche",
        "model": "911 Carrera",
        "year": 2022,
        "mileage": 5000,
        "fuelType": "Petrol",
        "transmission": "Automatic",
        "bodyType": "Coupe",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": True,
        "exchangePossible": False,
        "financingAvailable": True,
        "seller": {
            "user_id": "seller_8",
            "name": "Porsche Zentrum Berlin",
            "phone": "+49301234568",
            "rating": 5.0,
            "verified": True,
            "sellerType": "certified",
            "memberSince": "2017-04-10",
        },
    },
    {
        "id": "auto_9",
        "user_id": "seller_9",
        "title": "Hyundai Tucson N Line - Stylish SUV",
        "description": "Modern crossover with sport styling. The Tucson N Line offers a perfect blend of style, practicality, and efficiency. Features include hybrid powertrain, digital cluster, BOSE sound system, and smart safety features.",
        "price": 29500,
        "negotiable": True,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[13]],
        "location": "Leipzig, Germany",
        "city": "Leipzig",
        "distance": 30,
        "status": "active",
        "featured": False,
        "boosted": False,
        "views": 87,
        "favorites_count": 12,
        "make": "Hyundai",
        "model": "Tucson",
        "year": 2023,
        "mileage": 15000,
        "fuelType": "Hybrid",
        "transmission": "Automatic",
        "bodyType": "SUV",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": False,
        "exchangePossible": False,
        "financingAvailable": True,
        "seller": {
            "user_id": "seller_9",
            "name": "Thomas W.",
            "phone": "+49341234567",
            "rating": 4.3,
            "verified": False,
            "sellerType": "individual",
            "memberSince": "2023-01-20",
        },
    },
    {
        "id": "auto_10",
        "user_id": "seller_10",
        "title": "Honda Civic Type R - Track Ready",
        "description": "High-performance hot hatch with racing DNA. The Civic Type R is engineered for the track but practical for daily use. Features include 2.0L VTEC Turbo, adaptive dampers, limited-slip differential, and aggressive aero kit.",
        "price": 38900,
        "negotiable": False,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[14]],
        "location": "Nuremberg, Germany",
        "city": "Nuremberg",
        "distance": 45,
        "status": "active",
        "featured": False,
        "boosted": True,
        "views": 167,
        "favorites_count": 34,
        "make": "Honda",
        "model": "Civic Type R",
        "year": 2023,
        "mileage": 3000,
        "fuelType": "Petrol",
        "transmission": "Manual",
        "bodyType": "Hatchback",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": True,
        "exchangePossible": True,
        "financingAvailable": False,
        "seller": {
            "user_id": "seller_10",
            "name": "Performance Cars Bayern",
            "phone": "+49911234567",
            "rating": 4.8,
            "verified": True,
            "sellerType": "dealer",
            "memberSince": "2020-08-15",
        },
    },
    {
        "id": "auto_11",
        "user_id": "seller_11",
        "title": "Kia EV6 GT-Line - Future Electric",
        "description": "Award-winning electric crossover with stunning design. The EV6 offers fast charging, impressive range, and a tech-packed interior. Features include vehicle-to-load capability, augmented reality HUD, and premium relaxation seats.",
        "price": 47500,
        "negotiable": True,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[8]],
        "location": "Dresden, Germany",
        "city": "Dresden",
        "distance": 35,
        "status": "active",
        "featured": False,
        "boosted": False,
        "views": 145,
        "favorites_count": 29,
        "make": "Kia",
        "model": "EV6",
        "year": 2023,
        "mileage": 10000,
        "fuelType": "Electric",
        "transmission": "Automatic",
        "bodyType": "SUV",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": True,
        "exchangePossible": False,
        "financingAvailable": True,
        "seller": {
            "user_id": "seller_11",
            "name": "Kia Dresden",
            "phone": "+49351234567",
            "rating": 4.7,
            "verified": True,
            "sellerType": "dealer",
            "memberSince": "2021-03-01",
        },
    },
    {
        "id": "auto_12",
        "user_id": "seller_12",
        "title": "Nissan GT-R NISMO - Track Monster",
        "description": "Japanese supercar with racing DNA. The GT-R NISMO is a hand-built masterpiece delivering supercar performance. Features include hand-assembled 3.8L twin-turbo V6, carbon fiber aero, and track-tuned suspension.",
        "price": 125000,
        "negotiable": True,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[6], CAR_IMAGES[7]],
        "location": "Munich, Germany",
        "city": "Munich",
        "distance": 10,
        "status": "active",
        "featured": True,
        "boosted": False,
        "views": 534,
        "favorites_count": 98,
        "make": "Nissan",
        "model": "GT-R NISMO",
        "year": 2021,
        "mileage": 8500,
        "fuelType": "Petrol",
        "transmission": "Automatic",
        "bodyType": "Coupe",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": True,
        "exchangePossible": False,
        "financingAvailable": True,
        "seller": {
            "user_id": "seller_12",
            "name": "Supercar Gallery Munich",
            "phone": "+49891234568",
            "rating": 5.0,
            "verified": True,
            "sellerType": "certified",
            "memberSince": "2016-07-20",
        },
    },
    {
        "id": "auto_13",
        "user_id": "seller_13",
        "title": "VW ID.4 Pro - Family Electric",
        "description": "Spacious electric SUV for families. The ID.4 offers generous interior space, practical features, and zero emissions. Features include ID. Cockpit, wireless App-Connect, and IQ.DRIVE assist systems.",
        "price": 35900,
        "negotiable": True,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[12]],
        "location": "Hanover, Germany",
        "city": "Hanover",
        "distance": 22,
        "status": "active",
        "featured": False,
        "boosted": False,
        "views": 112,
        "favorites_count": 19,
        "make": "Volkswagen",
        "model": "ID.4",
        "year": 2023,
        "mileage": 18000,
        "fuelType": "Electric",
        "transmission": "Automatic",
        "bodyType": "SUV",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": False,
        "exchangePossible": True,
        "financingAvailable": True,
        "seller": {
            "user_id": "seller_13",
            "name": "VW Zentrum Hanover",
            "phone": "+49511234567",
            "rating": 4.6,
            "verified": True,
            "sellerType": "dealer",
            "memberSince": "2019-11-15",
        },
    },
    {
        "id": "auto_14",
        "user_id": "seller_14",
        "title": "BMW M4 Competition - Ultimate Driving",
        "description": "High-performance coupe with track capability. The M4 Competition delivers exhilarating performance with its twin-turbo inline-6. Features include M Carbon bucket seats, M Drive Professional, and adaptive M suspension.",
        "price": 72500,
        "negotiable": False,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[0], CAR_IMAGES[5]],
        "location": "Stuttgart, Germany",
        "city": "Stuttgart",
        "distance": 28,
        "status": "active",
        "featured": True,
        "boosted": True,
        "views": 389,
        "favorites_count": 76,
        "make": "BMW",
        "model": "M4",
        "year": 2022,
        "mileage": 12000,
        "fuelType": "Petrol",
        "transmission": "Automatic",
        "bodyType": "Coupe",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": True,
        "exchangePossible": False,
        "financingAvailable": True,
        "seller": {
            "user_id": "seller_14",
            "name": "BMW Stuttgart Premium",
            "phone": "+49711234568",
            "rating": 4.9,
            "verified": True,
            "sellerType": "certified",
            "memberSince": "2018-02-10",
        },
    },
    {
        "id": "auto_15",
        "user_id": "seller_15",
        "title": "Audi e-tron GT - Electric Luxury",
        "description": "Premium electric gran turismo. The e-tron GT combines stunning design with electric performance. Features include quattro all-wheel drive, air suspension, Matrix LED headlights, and virtual cockpit plus.",
        "price": 85000,
        "negotiable": True,
        "category_id": "vehicles",
        "images": [CAR_IMAGES[11]],
        "location": "Berlin, Germany",
        "city": "Berlin",
        "distance": 7,
        "status": "active",
        "featured": False,
        "boosted": False,
        "views": 267,
        "favorites_count": 52,
        "make": "Audi",
        "model": "e-tron GT",
        "year": 2023,
        "mileage": 6000,
        "fuelType": "Electric",
        "transmission": "Automatic",
        "bodyType": "Sedan",
        "condition": "used",
        "accidentFree": True,
        "inspectionAvailable": True,
        "exchangePossible": True,
        "financingAvailable": True,
        "seller": {
            "user_id": "seller_15",
            "name": "Audi Berlin Electric",
            "phone": "+49301234569",
            "rating": 4.8,
            "verified": True,
            "sellerType": "dealer",
            "memberSince": "2020-09-01",
        },
    },
]

async def main():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client.classifieds_db  # Match the database name in server.py
    
    print("Connecting to MongoDB...")
    
    # Add timestamps to listings
    now = datetime.now(timezone.utc)
    for i, listing in enumerate(AUTO_LISTINGS):
        listing["created_at"] = now
        listing["updated_at"] = now
    
    # Clear existing auto listings
    result = await db.auto_listings.delete_many({})
    print(f"Deleted {result.deleted_count} existing auto listings")
    
    # Insert new auto listings
    result = await db.auto_listings.insert_many(AUTO_LISTINGS)
    print(f"Inserted {len(result.inserted_ids)} auto listings")
    
    # Verify
    count = await db.auto_listings.count_documents({})
    print(f"Total auto listings in database: {count}")
    
    # Also add to main listings collection for unified search
    await db.listings.delete_many({"category_id": "vehicles"})
    for listing in AUTO_LISTINGS:
        listing["_id"] = listing["id"]
    await db.listings.insert_many(AUTO_LISTINGS)
    print(f"Also added to main listings collection")
    
    client.close()
    print("Done!")

if __name__ == "__main__":
    asyncio.run(main())
